export const bottomTypes: string[] = ['返回', 'face', 'pose', 'stuff', 'plant', 'animal', 'food', '\u274C'];
export const faceEmos: string[] = ['0x1F600', '0x1F637', '0x1F641', '0x1F644', '0x1F910', '0x1F915', '0x1F920', '0x1F92F', '0x1F9D0'];
export const poseEmos: string[] = ['0x1F645', '0x1F64F', '0x1F918', '0x1F91F', '0x1F930', '0x1F93E', '0x1F9D5', '0x1F9DF'];
export const stuffEmos: string[] = ['0x1F680', '0x1F6AA', '0x1F940', '0x1F94F', '0x1F9E0', '0x1F9E6'];
export const plantEmos: string[] = ['0x1F331', '0x1F353'];
export const animalEmos: string[] = ['0x1F980', '0x1F997'];
export const foodEmos: string[] = ['0x1F354', '0x1F37F', '0x1F950', '0x1F96B', '0x1F9C0'];
export const emos: string[][] = [[], faceEmos, poseEmos, stuffEmos, plantEmos, animalEmos, foodEmos];
