export namespace PresetConstant {

    /** Height (in point) of the ToolBar on the top of the keyboard */
    export const toolBarHeight: number = 56;

    /** KeyView corner radius */
    export const keyCornerRadius: number = 8;

    /** Larger KeyView corner radius */
    export const largeKeyCornerRadius: number = 10;

    /** Largest KeyView corner radius */
    export const ultraKeyCornerRadius: number = 12;
}
