export namespace UserSettingsKey {

    export const inputMemoryDatabaseFileName: string = "memory.sqlite3";

    export const preferencesInstanceName: string = "kbsettings";

    export const audio: string = "audio";

    export const haptic: string = "haptic";

    export const charset: string = "charset";

    export const keyboardLayout: string = "layout";

    export const numericLayout: string = "numeric";

    export const globeKey: string = "globe_key";

    export const emojiFrequent: string = "emoji_frequent";
}
